version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AiPi411

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: AiPi411
      ME_CONFIG_MONGODB_URL: mongodb://root:AiPi411@mongo:27017/
    volumes:
      - mongo-data: /data/db

volumes:
  mongo-data: